# -*- coding: utf-8 -*-
"""Copy of algoritmos_tesis.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16xBBoONfeDSUXT2LHzTGdTN601wJmlew

Requirements
'''
pip install transformers accelerate
pip install pysentimiento
pip install nltk
pip install transformers[sentencepiece]
pip install spacy
pip install asent
pip install optimum[onnxruntime]
'''
"""
import pandas as pd
import numpy as np

# Importando funciones refactorizadas
from .classifiers import (
    LexiconJSONClasificator,
    SentimentAnalysisSpanish,
    SenticonClasificator
)

from .fuzzy_logic import (
    interception,
    det,
    line_intersection,
    membership_triangle_function,
    generate_fuzzy_set,
    transform_to_fuzzy_set,
    fuzzy_set_2_tuple,
    media_aritmetica,
    media_ponderada
)

from .utils import (
    score,
    Metric
)

def difuso_clasificator(data:str, ColumnName:str, C=False, limite:int=None):
  pd.set_option('future.no_silent_downcasting', True)
  
  print(f"[SISTEMA] Cargando datos desde {data}...")
  df = pd.read_excel(data, sheet_name='Sheet1')
  
  # Aplicar límite si el usuario lo solicita
  if limite is not None:
      print(f"[SISTEMA] Limitando el proceso a las primeras {limite} filas...")
      df = df.head(limite).copy()
  
  # Extraer la columna de textos
  textos_completos = df[ColumnName].astype(str).tolist()

  # --- OPTIMIZACIÓN DE CACHÉ (DEDUPLICACIÓN) ---
  textos_unicos = list(set(textos_completos))
  total_original = len(textos_completos)
  total_unicos = len(textos_unicos)
  ahorro = total_original - total_unicos
  print(f"[SISTEMA] Deduplicación: Se encontraron {total_unicos} textos únicos de {total_original}.")
  print(f"[SISTEMA] ¡Te ahorrarás procesar {ahorro} textos repetidos!\n")

  print("[SISTEMA] Iniciando clasificación SECUENCIAL (Para evitar saturación de CPU)...")
  
  # Ejecución Secuencial
  clasif_senticon_unicos, scores_senticon_unicos = SenticonClasificator(textos_unicos, C)
  clasif_sentiment_unicos, scores_sentiment_unicos = SentimentAnalysisSpanish(textos_unicos)
  clasif_lexicon_unicos, scores_lexicon_unicos = LexiconJSONClasificator(textos_unicos)
      
  print("\n[SISTEMA] Clasificación terminada. Mapeando resultados...")

  # --- MAPEAR RESULTADOS A TODOS LOS DATOS ---
  dict_lexicon = dict(zip(textos_unicos, clasif_lexicon_unicos))
  dict_sentiment = dict(zip(textos_unicos, clasif_sentiment_unicos))
  dict_senticon = dict(zip(textos_unicos, clasif_senticon_unicos))
  
  dict_lexicon_scores = dict(zip(textos_unicos, scores_lexicon_unicos))
  dict_sentiment_scores = dict(zip(textos_unicos, scores_sentiment_unicos))
  dict_senticon_scores = dict(zip(textos_unicos, scores_senticon_unicos))
  
  clasif_lexicon = [dict_lexicon[t] for t in textos_completos]
  clasif_sentiment = [dict_sentiment[t] for t in textos_completos]
  clasif_senticon = [dict_senticon[t] for t in textos_completos]

  scores_lexicon = [dict_lexicon_scores[t] for t in textos_completos]
  scores_sentiment = [dict_sentiment_scores[t] for t in textos_completos]
  scores_senticon = [dict_senticon_scores[t] for t in textos_completos]

  # Crear DataFrame con los resultados
  df_select = pd.DataFrame({
      'Clasificacion_Lexico_JSON': clasif_lexicon,
      'Clasificacion_Sentiment_Spanish': clasif_sentiment,
      'Clasificacion_Senticon_XML': clasif_senticon
  })
  
  # Crear DataFrame con los scores numéricos
  df_scores = pd.DataFrame({
      'Score_Lexicon_JSON': scores_lexicon,
      'Score_Sentiment_Spanish': scores_sentiment,
      'Score_Senticon_XML': scores_senticon
  })
  
  # Sustituir etiquetas por valores numéricos
  df2 = df_select.replace(['POS','NEU','NEG'], [2,1,0])
  df2 = df2.apply(pd.to_numeric, errors='coerce').fillna(1).astype(int)

  polarity=generate_fuzzy_set(5)
  model=generate_fuzzy_set(3)

  var=[]
  
  print("[SISTEMA] Aplicando lógica difusa sobre valores continuos...")
  
  def score_to_2tuple(score, max_val):
      # Limitar el score para evitar que valores extremos rompan la escala
      clipped = max(-max_val, min(max_val, score))
      # Normalizar de [-max_val, max_val] a [0, 1]
      norm = (clipped + max_val) / (2 * max_val)
      # Mapear al espacio de 5 términos lingüísticos de la polaridad [0, 4]
      beta = norm * 4.0
      index = int(np.round(beta))
      alpha = beta - index
      return (index, alpha)

  for i, row in df_scores.iterrows():
    # Extraer los decimales reales
    val_lexicon = row['Score_Lexicon_JSON']
    val_sentiment = row['Score_Sentiment_Spanish']
    val_senticon = row['Score_Senticon_XML']
    
    # Convertir cada decimal a un voto difuso (2-tuple)
    # Los diccionarios (Lexicon/Senticon) pueden sumar puntos altos, limitamos a 2.5
    # SentimentSpanish ya está estrictamente entre -1.0 y 1.0
    fuzzy_sets_2_tuple = [
        score_to_2tuple(val_lexicon, max_val=2.5),
        score_to_2tuple(val_sentiment, max_val=1.0),
        score_to_2tuple(val_senticon, max_val=2.5)
    ]
    
    # Pesos basados en el rendimiento de cada modelo (Estrategia 4):
    # - Lexicon_JSON: 35% (Buena precisión, filtra falsos positivos)
    # - Sentiment_Spanish: 50% (Excelente Recall para detectar negativos)
    # - Senticon_XML: 15% (El más débil, se le da menos peso)
    weights = [0.35, 0.50, 0.15]
    
    # Calcular la media difusa ponderada de los 3 clasificadores
    res = media_ponderada(fuzzy_sets_2_tuple, weights)
    var.append(res[0]) 

  print(f"[SISTEMA] Guardando resultados finales en 'score_diffuse.xlsx'...")
  difuso = pd.DataFrame({'Clasicacion_Difusa': var})
  
  # Añadir df2 (etiquetas numéricas 2,1,0 para las métricas) y df_scores (números decimales reales) al excel final
  final = pd.concat([df, df2, df_scores, difuso], axis=1)
  final.to_excel('score_diffuse.xlsx')
  
  print("[SISTEMA] Calculando métricas (score)...")
  score(final)
  print("[SISTEMA] ¡Proceso completado exitosamente!")