# -*- coding: utf-8 -*-
"""Copy of algoritmos_tesis.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16xBBoONfeDSUXT2LHzTGdTN601wJmlew

Requirements
'''
pip install transformers accelerate
pip install pysentimiento
pip install nltk
pip install transformers[sentencepiece]
pip install spacy
pip install asent
'''
"""
import pandas as pd
import torch
import multiprocessing

# Importando funciones refactorizadas
from .classifiers import (
    PysentimentClasificator,
    BertClasificator,
    AsentClasificator
)

from .fuzzy_logic import (
    interception,
    det,
    line_intersection,
    membership_triangle_function,
    generate_fuzzy_set,
    transform_to_fuzzy_set,
    fuzzy_set_2_tuple,
    media_aritmetica
)

from .utils import (
    score,
    Metric
)

def difuso_clasificator(data:str, ColumnName:str, C=False):
  pd.set_option('future.no_silent_downcasting', True)
  
  # --- OPTIMIZACIÓN DE CPU EXTREMA ---
  # Al ejecutar en modo secuencial, le damos TODO el procesador a PyTorch 
  # para que acelere la inferencia de Pysentimiento y BERT sin interrupciones.
  cores = multiprocessing.cpu_count()
  torch.set_num_threads(cores)
  print(f"\n[SISTEMA] Turbo CPU Activado: PyTorch usará el 100% de la CPU ({cores} núcleos).")
  
  print(f"[SISTEMA] Cargando datos desde {data}...")
  df = pd.read_excel(data, sheet_name='Sheet1')
  
  # Extraer la columna de textos
  textos_completos = df[ColumnName].astype(str).tolist()

  # --- OPTIMIZACIÓN DE CACHÉ (DEDUPLICACIÓN) ---
  textos_unicos = list(set(textos_completos))
  total_original = len(textos_completos)
  total_unicos = len(textos_unicos)
  ahorro = total_original - total_unicos
  print(f"[SISTEMA] Deduplicación: Se encontraron {total_unicos} textos únicos de {total_original}.")
  print(f"[SISTEMA] ¡Te ahorrarás procesar {ahorro} textos repetidos!\n")

  print("[SISTEMA] Iniciando clasificación SECUENCIAL (Para evitar saturación de CPU)...")
  
  # Ejecución Secuencial: Mucho más rápida en CPU que paralela para redes neuronales
  clasif_asent_unicos = AsentClasificator(textos_unicos, C)
  clasif_bert_unicos = BertClasificator(textos_unicos)
  clasif_pysentimiento_unicos = PysentimentClasificator(textos_unicos)
      
  print("\n[SISTEMA] Clasificación terminada. Mapeando resultados...")

  # --- MAPEAR RESULTADOS A TODOS LOS DATOS ---
  dict_pysentiment = dict(zip(textos_unicos, clasif_pysentimiento_unicos))
  dict_bert = dict(zip(textos_unicos, clasif_bert_unicos))
  dict_asent = dict(zip(textos_unicos, clasif_asent_unicos))
  
  clasif_pysentimiento = [dict_pysentiment[t] for t in textos_completos]
  clasif_bert = [dict_bert[t] for t in textos_completos]
  clasif_asent = [dict_asent[t] for t in textos_completos]

  # Crear DataFrame con los resultados
  df_select = pd.DataFrame({
      'clasificacion_pysentimiento': clasif_pysentimiento,
      'Clasificacion_Bert': clasif_bert,
      'Clasificacion_Asentiment': clasif_asent
  })
  
  # Sustituir etiquetas por valores numéricos
  df2 = df_select.replace(['POS','NEU','NEG'], [2,1,0])
  df2 = df2.apply(pd.to_numeric, errors='coerce').fillna(1).astype(int)

  polarity=generate_fuzzy_set(5)
  model=generate_fuzzy_set(3)

  var=[]
  
  print("[SISTEMA] Aplicando lógica difusa...")
  for i, row in df2.iterrows():
    experts_votation = row.values
    fuzzy_sets_2_tuple=[]
    for index in experts_votation:
      fuzzy_set=transform_to_fuzzy_set(model[index],polarity)
      fuzzy_sets_2_tuple.append(fuzzy_set_2_tuple(fuzzy_set))
    
    res = media_aritmetica(fuzzy_sets_2_tuple)
    var.append(res[0]) 

  print(f"[SISTEMA] Guardando resultados finales en 'score_diffuse.xlsx'...")
  difuso = pd.DataFrame({'Clasicacion_Difusa': var})
  
  final = pd.concat([df, df2, difuso], axis=1)
  final.to_excel('score_diffuse.xlsx')
  
  print("[SISTEMA] Calculando métricas (score)...")
  score(final)
  print("[SISTEMA] ¡Proceso completado exitosamente!")