# -*- coding: utf-8 -*-
"""Copy of algoritmos_tesis.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16xBBoONfeDSUXT2LHzTGdTN601wJmlew

Requirements
'''
pip install transformers accelerate
pip install pysentimiento
pip install nltk
pip install transformers[sentencepiece]
pip install spacy
pip install asent
'''
"""
import pandas as pd
import concurrent.futures

# Importando funciones refactorizadas
from .classifiers import (
    PysentimentClasificator,
    BertClasificator,
    AsentClasificator
)

from .fuzzy_logic import (
    interception,
    det,
    line_intersection,
    membership_triangle_function,
    generate_fuzzy_set,
    transform_to_fuzzy_set,
    fuzzy_set_2_tuple,
    media_aritmetica
)

from .utils import (
    score,
    Metric
)
# Nota: ExcelConcat ha sido removido porque ya no trabajamos guardando archivos intermedios.

def difuso_clasificator(data:str, ColumnName:str, C=False):
  pd.set_option('future.no_silent_downcasting', True)
  
  print(f"Cargando datos desde {data}...")
  df = pd.read_excel(data, sheet_name='Sheet1')
  
  # Extraer la columna de textos como una lista de strings
  textos = df[ColumnName].astype(str).tolist()

  print("Iniciando clasificación en paralelo (usando GPU si está disponible)...")
  
  # Usamos ThreadPoolExecutor para paralelizar. 
  # En Python, para operaciones intensivas con PyTorch, ThreadPoolExecutor es seguro y libera el GIL.
  with concurrent.futures.ThreadPoolExecutor(max_workers=3) as executor:
      # Lanzamos las 3 tareas al mismo tiempo
      future_pysentiment = executor.submit(PysentimentClasificator, textos)
      future_bert = executor.submit(BertClasificator, textos)
      future_asent = executor.submit(AsentClasificator, textos, C)
      
      # Esperamos a que terminen y obtenemos los resultados
      clasif_pysentimiento = future_pysentiment.result()
      clasif_bert = future_bert.result()
      clasif_asent = future_asent.result()
      
  print("Clasificación terminada. Integrando resultados...")

  # Crear DataFrame con los resultados
  df_select = pd.DataFrame({
      'clasificacion_pysentimiento': clasif_pysentimiento,
      'Clasificacion_Bert': clasif_bert,
      'Clasificacion_Asentiment': clasif_asent
  })
  
  # Sustituir etiquetas por valores numéricos, forzar tipo numérico y llenar posibles nulos con 1 (Neutral)
  df2 = df_select.replace(['POS','NEU','NEG'], [2,1,0])
  df2 = df2.apply(pd.to_numeric, errors='coerce').fillna(1).astype(int)

  polarity=generate_fuzzy_set(5) # la polaridad tiene un agranularidad de 5 (muy negativo (0), negativo(1),neutral(2),positivo(3), muy positivo(4))
  model=generate_fuzzy_set(3) # los modelos clasifican con 3 etiquetas

  var=[]
  
  print("Aplicando lógica difusa...")
  for i, row in df2.iterrows(): #recorrer cada fila del dataframe
    experts_votation = row.values #selecciona cada dato de la fila
    fuzzy_sets_2_tuple=[]
    for index in experts_votation: #selecciona la votacion de los expertos
      fuzzy_set=transform_to_fuzzy_set(model[index],polarity)
      fuzzy_sets_2_tuple.append(fuzzy_set_2_tuple(fuzzy_set))
    
    # Calcular y guardar la media aritmética
    res = media_aritmetica(fuzzy_sets_2_tuple)
    var.append(res[0]) 

  print("Guardando resultados finales...")
  difuso = pd.DataFrame({'Clasicacion_Difusa': var})
  
  # Concatenar el dataframe original, las predicciones numéricas (df2) y el resultado difuso
  final = pd.concat([df, df2, difuso], axis=1)
  final.to_excel('score_diffuse.xlsx')
  
  print("Calculando métricas (score)...")
  score(final)
  print("¡Proceso completado exitosamente!")